autoload -U colors && colors
PROMPT='[%F{red}%1d%f]$ '
zstyle ':completion::complete:*' gain-privileges 1
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) #hidden file

#vi mode
bindkey -v
export KEYTIMEOUT=1
# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char
bindkey '^R' history-incremental-search-backward
#aliases

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ff='fastfetch'
alias aria2c='aria2c --disable-ipv6'
alias fcd='cd $(find . -type d -print | fzf)'
alias nrs='sudo nixos-rebuild switch --flake ./'
alias hms='home-manager switch --flake ./' 
alias ss='ssh -p 2222 jpawee@192.168.1.42'



